services:
  postgres:
    image: postgres:latest
    container_name: ovistake
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5400:5432'
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
    driver: local
